module.exports = [
  "{title:text}",
  "{url:link}", 
  "{footer:text:url}",
  "{description:text}",
	"{color:hex}",
  "{author:text:url}",
  "{file:text:name.extension}", 
  "{thumbnail:url}",
  "{deletecommand} or {deletecommand:time}", 
  "{field:name:value:inline}",
  "{timestamp:ms}",
  "{execute:awaited command name}",
  "{image:url}",
  "{reactions:emoji,emoji2,...}", 
  "{suppress:yes/no}", 
  "{delete:time}", 
  "{attachment:name.extension:url}", 
  "{edit:duration:{new message}:{new message}:{...}}"
]