module.exports = {
  id: "The ID of the updated guild;.id",
  name: "The name of the updated guild;.name",
  icon: "The icon of the updated guild;.iconURL()",
  afkchannelid: "The channelID of the AFK channel of the updated guild;.afkChannelID",
  afktimeout: "The AFK timeout of the updated guild;.afkTimeout",
  systemchannelid: "The ID of the system channel of the updated guild;.systemChannelID",
  ruleschannelid: "The ID of the rules channel of the updated guild;.rulesChannelID",
  updateschannelid: "The ID of the system channel of the updated guild;.publicUpdatesChannelID",
  description: "The server's discovery description of the updated guild;.description",
  notifications: "The default message notifications level of the updated guild;.defaultMessageNotifications",
  contentfilter: "The explicit content filter of the updated guild;.explicitContentFilter", 
  verificationlvl: "The verification level of the updated guild;.verificationLevel",
  owner: "The user tag of the owner of the updated guild;.owner.user.tag",
  ownerid: "The usercID of the owner of the updated guild;.owner.user.id", 
  mfalevel: "The 2FA level of the updated guild;.mfaLevel",
  vanityurl: "The vanity url of the updated guild;.vanityURLCode",
  region: "The default voice channel region of the updated guild;.region",
  locale: "The preferred locale of the updated guild;.preferredLocale",
  verified: "Whether the updated guild is Discord verified or not;.verified",
  partnered: "Whether the updated guild is Discord partnered or not;.deleteable",
  invitesplash: "The invite splash banner of the updated guild.;.splashURL({size: 2048})",
  banner: "The server banner of the updated guild.;.bannerURL({dynamic: true, size: 2048})"
};